name: FFMPEG RTMP Streaming Without Watermark

on:
  workflow_dispatch:  # Memungkinkan menjalankan workflow secara manual
  schedule:
    - cron: '0 * * * *'  # Jalankan setiap jam (opsional)

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up FFMPEG
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Start Streaming with FFMPEG
        env:
          INPUT_URL: ${{ secrets.INPUT_URL }}
          RTMP_URL: ${{ secrets.RTMP_URL }}
        run: |
          ffmpeg -re -i "$INPUT_URL" \
          -c:v copy -c:a aac -b:a 128k \
          -f flv "$RTMP_URL"
